### ISSUE TITLE
create MerkleTree project - aiken - Milestone 1

### ISSUE THREAD

**Issue by solidsnakedev** [Anastasia-Labs/data-structures#3]
Take this as reference,
https://github.com/Anastasia-Labs/plutarch-merkle-tree/tree/main

The project must show evidence of the following:

- MerkleTree library compiles successfully
- MerkleTree unit testing pass validations
- Example validator script pass validation
- Detailed instructions on running the tests are provided.

you can also create a short animation with https://github.com/asciinema/asciinema

**Comment by solidsnakedev** [comment]
project repo https://github.com/Anastasia-Labs/aiken-merkle-tree

**Comment by micahkendall** [comment]
Hey, is the reference complete or also in progress?

**Comment by solidsnakedev** [comment]
It’s complete, however the documentation side must be polished
